client:
  id: "test"
  secret: "e6423085f5165a58f8949e763c6691ffe44e2f86"
  apiEndpoint: "https://api.dustlight.cn"
  tokenUri: "https://api.dustlight.cn/v1/oauth/token"
  checkTokenUri: "https://api.dustlight.cn/v1/token/validity"
  jwkSetUri: "https://api.dustlight.cn/v1/jwk"

dustlight:
  auth:
    oauth2:
      client:
        client-id: ${client.id}
        client-secret: ${client.secret}
        api-endpoint: ${client.apiEndpoint}
        token-uri: ${client.tokenUri}
      resource-server:
        client-id: ${client.id}
        client-secret: ${client.secret}
        uri: ${client.checkTokenUri}
        jwk-set-uri: ${client.jwkSetUri}
  flow:
    authorization-endpoint: "https://accounts.dustlight.cn/authorize"
    zeebe:
      address: localhost:26500
      plaintext: true
      system-prefix:
        - "csystem-"
    datacenter:
      endpoint: "https://datacenter.dustlight.cn"
  datacenter:
    amqp:
      exchange: datacenter-my-dc
      sync:
        enabled: true
        queue: my-flow
        dead-letter-queue: my-flow-dead
        dead-letter-routing-key: my-flow-SYNC-FAIL
# SpringDoc 配置
springdoc:
  api-docs:
    enabled: on
    path: /doc
  swagger-ui:
    path: /doc.html
    oauth:
      client-id: ${client.id}
      additional-query-string-params:
        jwt: true
spring:
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - localhost:9200
logging:
  level:
    cn.dustlight.flow.*: debug
