# OAuth 配置
plus:
  oauth2:
    client:
      client-id: 877ce1dd5030000
      client-secret: 1283d148237af330152929cfe05ec045b0a4e92d
      api-endpoint: http://api.wgv
      token-uri: http://api.wgv/v1/oauth/token
    resource-server:
      jwk-set-uri: http://api.wgv/v1/jwk
      client-secret: none
      client-id: none
      uri: http://api.wgv/v1/token/validity
      token-type: jwt
  datacenter:
    amqp:
      exchange: datacenter-test
      sync:
        enabled: true
        queue: flow-test
        dead-letter-queue: flow-dead-test
  flow:
    authorization-endpoint: "http://accounts.wgv.ink/authorize"
    zeebe:
      address: zeebe.svc:26500
      plaintext: true
      system-prefix:
        - "system."
  messenger:
    client:
      client-id: 8906c510dc30000
      client-secret: dc09dbd5abeba019afbd678325961b05b1bfdbf0
# SpringDoc 配置
springdoc:
  api-docs:
    enabled: on
    path: /doc
  swagger-ui:
    path: /doc.html
    oauth:
      client-id: 86c3e34e2030000
      additional-query-string-params:
        jwt: true
spring:
  rabbitmq:
    addresses: rabbitmq.svc
    port: 5672
    username: flow-test
    password: flow-test
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - elasticsearch.zeebe.svc
