/**
 * 流程服务
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: hansin@goodvoice.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Configuration } from './configuration';
import { AxiosPromise, AxiosInstance } from 'axios';
import { RequestArgs, BaseAPI } from './base';
/**
 *
 * @export
 * @interface InstanceError
 */
export interface InstanceError {
    /**
     *
     * @type {string}
     * @memberof InstanceError
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof InstanceError
     */
    type?: string;
}
/**
 *
 * @export
 * @interface InstanceObject
 */
export interface InstanceObject {
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof InstanceObject
     */
    version?: number;
    /**
     *
     * @type {Array<object>}
     * @memberof InstanceObject
     */
    events?: Array<object>;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    clientId?: string;
    /**
     *
     * @type {number}
     * @memberof InstanceObject
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    elementType?: string;
    /**
     *
     * @type {InstanceError}
     * @memberof InstanceObject
     */
    error?: InstanceError;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    status?: InstanceObjectStatusEnum;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    elementId?: string;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    updatedAt?: string;
    /**
     *
     * @type {string}
     * @memberof InstanceObject
     */
    createdAt?: string;
}
/**
    * @export
    * @enum {string}
    */
export declare enum InstanceObjectStatusEnum {
    Active = "ACTIVE",
    Canceled = "CANCELED",
    Completed = "COMPLETED",
    Incident = "INCIDENT",
    Resolved = "RESOLVED"
}
/**
 *
 * @export
 * @interface ProcessObject
 */
export interface ProcessObject {
    /**
     *
     * @type {string}
     * @memberof ProcessObject
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof ProcessObject
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof ProcessObject
     */
    owner?: string;
    /**
     *
     * @type {number}
     * @memberof ProcessObject
     */
    version?: number;
    /**
     *
     * @type {object}
     * @memberof ProcessObject
     */
    data?: object;
    /**
     *
     * @type {string}
     * @memberof ProcessObject
     */
    clientId?: string;
    /**
     *
     * @type {string}
     * @memberof ProcessObject
     */
    createdAt?: string;
}
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary 通过 ID 取消运行实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelInstance: (id: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 创建流程实例
     * @param {string} name
     * @param {{ [key: string]: object; }} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createInstance: (name: string, requestBody: {
        [key: string]: object;
    }, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 发布消息
     * @param {string} name
     * @param {string} key
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createMessage: (name: string, key: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 创建流程
     * @param {string} body
     * @param {string} [cid]
     * @param {boolean} [base64]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProcess: (body: string, cid?: string, base64?: boolean, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 通过 ID 获取流程实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstance: (id: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 查询流程实例
     * @param {string} [name]
     * @param {number} [version]
     * @param {Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>} [status]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstances: (name?: string, version?: number, status?: Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>, page?: number, size?: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 通过名称获取流程
     * @param {string} name
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess: (name: string, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 通过名称与版本号获取流程
     * @param {string} name
     * @param {number} version
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess1: (name: string, version: number, cid?: string, options?: any) => Promise<RequestArgs>;
    /**
     *
     * @summary 获取流程列表
     * @param {string} [q]
     * @param {string} [cid]
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcesses: (q?: string, cid?: string, page?: number, size?: number, options?: any) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary 通过 ID 取消运行实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelInstance(id: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary 创建流程实例
     * @param {string} name
     * @param {{ [key: string]: object; }} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createInstance(name: string, requestBody: {
        [key: string]: object;
    }, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InstanceObject>>;
    /**
     *
     * @summary 发布消息
     * @param {string} name
     * @param {string} key
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createMessage(name: string, key: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary 创建流程
     * @param {string} body
     * @param {string} [cid]
     * @param {boolean} [base64]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProcess(body: string, cid?: string, base64?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary 通过 ID 获取流程实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstance(id: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InstanceObject>>;
    /**
     *
     * @summary 查询流程实例
     * @param {string} [name]
     * @param {number} [version]
     * @param {Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>} [status]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstances(name?: string, version?: number, status?: Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>, page?: number, size?: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InstanceObject>>>;
    /**
     *
     * @summary 通过名称获取流程
     * @param {string} name
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess(name: string, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessObject>>;
    /**
     *
     * @summary 通过名称与版本号获取流程
     * @param {string} name
     * @param {number} version
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess1(name: string, version: number, cid?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessObject>>;
    /**
     *
     * @summary 获取流程列表
     * @param {string} [q]
     * @param {string} [cid]
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcesses(q?: string, cid?: string, page?: number, size?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProcessObject>>>;
};
/**
 * DefaultApi - factory interface
 * @export
 */
export declare const DefaultApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary 通过 ID 取消运行实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelInstance(id: number, cid?: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary 创建流程实例
     * @param {string} name
     * @param {{ [key: string]: object; }} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createInstance(name: string, requestBody: {
        [key: string]: object;
    }, cid?: string, options?: any): AxiosPromise<InstanceObject>;
    /**
     *
     * @summary 发布消息
     * @param {string} name
     * @param {string} key
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createMessage(name: string, key: string, cid?: string, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary 创建流程
     * @param {string} body
     * @param {string} [cid]
     * @param {boolean} [base64]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProcess(body: string, cid?: string, base64?: boolean, options?: any): AxiosPromise<void>;
    /**
     *
     * @summary 通过 ID 获取流程实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstance(id: number, cid?: string, options?: any): AxiosPromise<InstanceObject>;
    /**
     *
     * @summary 查询流程实例
     * @param {string} [name]
     * @param {number} [version]
     * @param {Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>} [status]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInstances(name?: string, version?: number, status?: Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>, page?: number, size?: number, cid?: string, options?: any): AxiosPromise<Array<InstanceObject>>;
    /**
     *
     * @summary 通过名称获取流程
     * @param {string} name
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess(name: string, cid?: string, options?: any): AxiosPromise<ProcessObject>;
    /**
     *
     * @summary 通过名称与版本号获取流程
     * @param {string} name
     * @param {number} version
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcess1(name: string, version: number, cid?: string, options?: any): AxiosPromise<ProcessObject>;
    /**
     *
     * @summary 获取流程列表
     * @param {string} [q]
     * @param {string} [cid]
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProcesses(q?: string, cid?: string, page?: number, size?: number, options?: any): AxiosPromise<Array<ProcessObject>>;
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI {
    /**
     *
     * @summary 通过 ID 取消运行实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    cancelInstance(id: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @summary 创建流程实例
     * @param {string} name
     * @param {{ [key: string]: object; }} requestBody
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createInstance(name: string, requestBody: {
        [key: string]: object;
    }, cid?: string, options?: any): Promise<import("axios").AxiosResponse<InstanceObject>>;
    /**
     *
     * @summary 发布消息
     * @param {string} name
     * @param {string} key
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createMessage(name: string, key: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @summary 创建流程
     * @param {string} body
     * @param {string} [cid]
     * @param {boolean} [base64]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createProcess(body: string, cid?: string, base64?: boolean, options?: any): Promise<import("axios").AxiosResponse<void>>;
    /**
     *
     * @summary 通过 ID 获取流程实例
     * @param {number} id
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getInstance(id: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<InstanceObject>>;
    /**
     *
     * @summary 查询流程实例
     * @param {string} [name]
     * @param {number} [version]
     * @param {Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>} [status]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getInstances(name?: string, version?: number, status?: Set<'ACTIVE' | 'CANCELED' | 'COMPLETED' | 'INCIDENT' | 'RESOLVED'>, page?: number, size?: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<InstanceObject[]>>;
    /**
     *
     * @summary 通过名称获取流程
     * @param {string} name
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getProcess(name: string, cid?: string, options?: any): Promise<import("axios").AxiosResponse<ProcessObject>>;
    /**
     *
     * @summary 通过名称与版本号获取流程
     * @param {string} name
     * @param {number} version
     * @param {string} [cid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getProcess1(name: string, version: number, cid?: string, options?: any): Promise<import("axios").AxiosResponse<ProcessObject>>;
    /**
     *
     * @summary 获取流程列表
     * @param {string} [q]
     * @param {string} [cid]
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getProcesses(q?: string, cid?: string, page?: number, size?: number, options?: any): Promise<import("axios").AxiosResponse<ProcessObject[]>>;
}
