replicaCount: 1

image:
  repository: dustlightcn/flow-service
  tag: "0.1.8-alpha-1"

ingress:
  className: "nginx"
  host: "flow.dustlight.cn"
  tls:
    enabled: false
    crt: ""
    key: ""

config:
  elasticsearch:
    endpoints:
      - "elasticsearch-master:9200"
  zeebe:
    address: "zeebe-zeebe-gateway.zeebe:26500"
  datacenter:
    releaseName: "my-dc"
    endpoint: "http://my-dc-datacenter-service"
  rabbitmq:
    host: "rabbitmq-svc"
    port: 5672
    username: ""
    password: ""
  auth:
    clientId: "test"
    clientSecret: "e6423085f5165a58f8949e763c6691ffe44e2f86"
    apiEndpoint: "https://api.dustlight.cn"
    tokenUri: "https://api.dustlight.cn/v1/oauth/token"
    checkTokenUri: "https://api.dustlight.cn/v1/token/validity"
    jwkSetUri: "https://api.dustlight.cn/v1/jwk"
    authorizationEndpoint: "https://accounts.dustlight.cn/authorize"

logging: debug